### ISSUE TITLE
Error building Dwitter: No module named appconf

### ISSUE THREAD

**Issue by wesleywerner** [lionleaf/dwitter#176]
Hi. I get this error trying to build Dwitter, it also reminds me that some more detailed setup instructions are needed :)

```
...
Requirement already up-to-date: six in ./venv/lib/python2.7/site-packages (from django-anymail==0.3.1->-r requirements.txt (line 2))
Requirement already up-to-date: pytz in ./venv/lib/python2.7/site-packages (from django-dbbackup==2.5.0->-r requirements.txt (line 4))
Cleaning up...
python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/media/data/src/dwitter/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/media/data/src/dwitter/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 328, in execute
    django.setup()
  File "/media/data/src/dwitter/venv/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/media/data/src/dwitter/venv/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/media/data/src/dwitter/venv/local/lib/python2.7/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/media/data/src/dwitter/venv/local/lib/python2.7/site-packages/compressor/models.py", line 1, in <module>
    from compressor.conf import CompressorConf  # noqa
  File "/media/data/src/dwitter/venv/local/lib/python2.7/site-packages/compressor/conf.py", line 7, in <module>
    from appconf import AppConf
ImportError: No module named appconf
Makefile:14: recipe for target 'migrate' failed
make: *** [migrate] Error 1
```

I tried installing both these but the error persists (after resetting the virtual env):

```
sudo pip install --upgrade django-appconf
sudo apt-get install python-appconf
```

Thanks in advance for any hints of what else I can try.

**Comment by lionleaf** [comment]
Apologies for the lack of response to this. Did you ever work it out?
